

#ifndef	_SYSTICK_TYPES_H_
#define _SYSTICK_TYPES_H_

#define SYSTICK_ENABLE						SETBIT(SysTick.STCTRL,0)
#define SYSTICK_DISABLE						CLRBIT(SysTick.STCTRL,0)
#define SYSTICK_INTERRUPT_ENABLE	SETBIT(SysTick.STCTRL,1)
#define SYSTICK_INTERRUPT_DISABLE	CLRBIT(SysTick.STCTRL,1)
#define SET_RELOAD_VAL(RELOADVALUE)	SysTick.STRELOAD = RELOADVALUE
#define GET_COUNT_VAL	SysTick.STCURRENT
#define GET_COUNT_STATUS READBIT(SysTick.STCTRL,16)

#endif	//_SYSTICK_TYPES_H_
