/*
 * Timer_Types.h
 *
 *  Created on: Sep 26, 2022
 *      Author: ahmed
 */

#ifndef TIMER_TYPES_H_
#define TIMER_TYPES_H_

#define ENABLE_TIMER_CLOCK_GATE_CONTROL(tn)     SETBIT(RCGCTIMER,tn)
#define ENABLE_TIMER(TIMER_N,CHANNEL)           SETBIT((TIMER_N).GPTMCTL, CHANNEL)//Disable TimerA or TimerB
#define DISABLE_TIMER(TIMER_N,CHANNEL)          CLRBIT((TIMER_N).GPTMCTL, CHANNEL)//Disable TimerA or TimerB

#define RESET_CONFIG(TIMER_N);                  (TIMER_N).GPTMCFG=0;//Reset configuration
#define SELECT_MODE_A(TIMER_N,TIMER_MODE);      (TIMER_N).GPTMTAMR = TIMER_MODE
#define SELECT_MODE_B(TIMER_N,TIMER_MODE);      (TIMER_N).GPTMTBMR = TIMER_MODE
#define SET_RELOAD_COUNT_A(TIMER_N,COUNT)       (TIMER_N).GPTMTAILR = COUNT
#define SET_RELOAD_COUNT_B(TIMER_N,COUNT)       (TIMER_N).GPTMTBILR = COUNT
#define SET_PRESCALER_A(TIMER_N, PRESCALER)     (TIMER_N).GPTMTAPR = PRESCALER
#define SET_PRESCALER_B(TIMER_N, PRESCALER)     (TIMER_N).GPTMTBPR = PRESCALER
#define CONFIGURE_TIMER(TIMER_N, CONFIG)        (TIMER_N).GPTMCFG = CONFIG

#define ENABLE_INTERRUPT(TIMER_N, TYPE)         SETBIT((TIMER_N).GPTMIMR, TYPE)
#define DISABLE_INTERRUPT(TIMER_N, TYPE)        CLRBIT((TIMER_N).GPTMIMR, TYPE)
#define CLEAR_INTERRUPT_FLAG(TIMER_N, TYPE)     SETBIT((TIMER_N).GPTMICR, TYPE)
#define GET_INTERRUPT_STATUS(TIMER_N, TYPE)     READBIT((TIMER_N).GPTMRIS, TYPE)
#endif /* TIMER_TYPES_H_ */
