#ifndef INTCTRL_TYPES_H_
#define INTCTRL_TYPES_H_

#define INTERRUPT_ENABLE(INT_NUM)       SETBIT(NVIC.EN[INT_NUM/32],INT_NUM%32)
#define INTERRUPT_DISABLE(INT_NUM)      SETBIT(NVIC.DIS[INT_NUM/32],INT_NUM%32)
#define INTERRUPT_PEND(INT_NUM)         SETBIT(NVIC.PEND[INT_NUM/32],INT_NUM%32)
#define INTERRUPT_UNPEND(INT_NUM)       SETBIT(NVIC.UNPEND[INT_NUM/32],INT_NUM%32)
#define INTERRUPT_ENABLE_READ(INT_NUM)  READBIT(NVIC.EN[INT_NUM/32],INT_NUM%32)


#endif
